// AUTHENTICATION
export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_AUTH = 'USER_AUTH';

// PASSWORD
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

// IMPACT AREA
export const GET_ALL_GLOBAL_IMPACT_AREAS = 'GET_ALL_GLOBAL_IMPACT_AREAS';
export const GET_ALL_IMPACT_AREAS_BY_USER = 'GET_ALL_IMPACT_AREAS_BY_USER';

// SKILL
export const GET_ALL_GLOBAL_SKILLS = 'GET_ALL_GLOBAL_SKILLS';
export const GET_ALL_SKILLS_BY_USER = 'GET_ALL_SKILLS_BY_USER';

// LANGUAGE
export const GET_ALL_GLOBAL_LANGUAGES = 'GET_ALL_GLOBAL_LANGUAGES';
export const GET_ALL_LANGUAGES_BY_USER = 'GET_ALL_LANGUAGES_BY_USER';

export const GET_ALL_ORGANIZATION_TYPES = 'GET_ALL_ORGANIZATION_TYPES';

// USER
export const GET_BASIC_INFO = 'GET_BASIC_INFO';
export const GET_INVOLVEMENT = 'GET_INVOLVEMENT';
export const GET_PRIVACY = 'GET_PRIVACY';
export const GET_SERVICE_INFO = 'GET_SERVICE_INFO';
export const GET_INTERNAL_LINK = 'GET_INTERNAL_LINK';

export const SET_BASIC_INFO = 'SET_BASIC_INFO';
export const SET_INVOLVEMENT = 'SET_INVOLVEMENT';
export const SET_PRIVACY = 'SET_PRIVACY';
export const SET_SERVICE_INFO = 'SET_SERVICE_INFO';
export const SET_INTERNAL_LINK = 'SET_INTERNAL_LINK';

export const CLEAR_BASIC_INFO = 'CLEAR_BASIC_INFO';
export const CLEAR_INVOLVEMENT = 'CLEAR_INVOLVEMENT';
export const CLEAR_PRIVACY = 'CLEAR_PRIVACY';
export const CLEAR_SERVICE_INFO = 'CLEAR_SERVICE_INFO';
export const CLEAR_INTERNAL_LINK = 'CLEAR_INTERNAL_LINK';

export const GET_ALL_USERS = 'GET_ALL_USERS';
export const GET_USER_PUBLIC_INFO = 'GET_USER_PUBLIC_INFO';
export const GET_ALL_SUGGESTED_USERS = 'GET_ALL_SUGGESTED_USERS';

export const CLEAR_ALL_USERS = 'CLEAR_ALL_USERS';
export const CLEAR_USER_PUBLIC_INFO = 'CLEAR_USER_PUBLIC_INFO';
export const CLEAR_ALL_SUGGESTED_USERS = 'CLEAR_ALL_SUGGESTED_USERS';

// FOLLOW
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const GET_ALL_FOLLOWERS = 'GET_ALL_FOLLOWERS';
export const GET_ALL_FOLLOWINGS = 'GET_ALL_FOLLOWINGS';
export const CHECK_IF_FOLLOWER = 'CHECK_IF_FOLLOWER';

// POSTS
export const GET_POST = 'GET_POST';
export const SET_POST = 'SET_POST';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const CLEAR_POST = 'CLEAR_POST';
export const DELETE_POST = 'DELETE_POST';
export const HOME_FEED = 'HOME_FEED';
export const GET_ALL_SUGGESTED_POSTS = 'GET_ALL_SUGGESTED_POSTS';

export const LIKE_POST = 'LIKE_POST';
export const CANCEL_LIKE_POST = 'CANCEL_LIKE_POST';

export const INTERESTED_POST = 'INTERESTED_POST';
export const CANCEL_INTERESTED_POST = 'CANCEL_INTERESTED_POST';

export const GOING_POST = 'GOING_POST';
export const CANCEL_GOING_POST = 'CANCEL_GOING_POST';

export const CHANGE_POST_INTEREST = 'CHANGE_POST_INTEREST';

// NOTIFICATION
export const GET_TOP_NOTIFICATIONS = 'GET_TOP_NOTIFICATIONS';
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_NOTIFICATIONS_COUNT = 'GET_NOTIFICATIONS_COUNT';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_NOTIFICATION_LOCAL = 'SET_NOTIFICATION_LOCAL';

// MEMBERSHIP
export const GET_MEMBERSHIP = 'GET_MEMBERSHIP';
export const SET_MEMBERSHIP = 'SET_MEMBERSHIP';
export const GET_ALL_MEMBERSHIPS = 'GET_ALL_MEMBERSHIPS';

export const DELETE_MEMBERSHIP = 'DELETE_MEMBERSHIP';
export const ACCEPT_MEMBERSHIP = 'ACCEPT_MEMBERSHIP';
export const REJECT_MEMBERSHIP = 'REJECT_MEMBERSHIP';

// FRIENDSHIP
export const GET_FRIENDSHIP = 'GET_FRIENDSHIP';
export const SET_FRIENDSHIP = 'SET_FRIENDSHIP';
export const GET_ALL_FRIENDSHIPS = 'GET_ALL_FRIENDSHIPS';

export const DELETE_FRIENDSHIP = 'DELETE_FRIENDSHIP';
export const ACCEPT_FRIENDSHIP = 'ACCEPT_FRIENDSHIP';
export const REJECT_FRIENDSHIP = 'REJECT_FRIENDSHIP';
export const CHECK_IF_FRIENDS = 'CHECK_IF_FRIENDS';

// ENDORSEMENT
export const ENDORSE_USER = 'ENDORSE_USER';
export const CANCEL_ENDORSE_USER = 'CANCEL_ENDORSE_USER';
export const GET_ALL_ENDORSERS = 'GET_ALL_ENDORSERS';
export const GET_ALL_ENDORSEES = 'GET_ALL_ENDORSEES';
export const CHECK_IF_ENDORSES = 'CHECK_IF_ENDORSES';

// VIEWER
export const GET_ALL_VIEWERS_BY_POST = 'GET_ALL_VIEWERS_BY_POST';

// CONVERSATION
export const SET_CONVERSATION = 'SET_CONVERSATION';
export const GET_ALL_CONVERSATIONS_BY_USER = 'GET_ALL_CONVERSATIONS_BY_USER';
export const GET_CONVERSATION = 'GET_CONVERSATION';
export const SET_MESSAGE = 'SET_MESSAGE';
