export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_AUTH = 'USER_AUTH';
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const DELETE_USER = 'DELETE_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const CLEAR_ALL_USERS = 'CLEAR_ALL_USERS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const GET_ALL_AREA_OF_INTEREST = 'GET_ALL_AREA_OF_INTEREST';

// IMPACT AREA
export const GET_ALL_GLOBAL_IMPACT_AREAS = 'GET_ALL_GLOBAL_IMPACT_AREAS';
export const GET_ALL_IMPACT_AREAS_BY_USER = 'GET_ALL_IMPACT_AREAS_BY_USER';

// SKILL
export const GET_ALL_GLOBAL_SKILLS = 'GET_ALL_GLOBAL_SKILLS';
export const GET_ALL_SKILLS_BY_USER = 'GET_ALL_SKILLS_BY_USER';

// LANGUAGE
export const GET_ALL_GLOBAL_LANGUAGES = 'GET_ALL_GLOBAL_LANGUAGES';
export const GET_ALL_LANGUAGES_BY_USER = 'GET_ALL_LANGUAGES_BY_USER';

export const GET_ALL_ORGANIZATION_TYPES = 'GET_ALL_ORGANIZATION_TYPES';

// INDIVIDUAL
export const GET_INDIVIDUAL_BASIC_INFO = 'GET_INDIVIDUAL_BASIC_INFO';
export const GET_INDIVIDUAL_INVOLVEMENT = 'GET_INDIVIDUAL_INVOLVEMENT';
export const GET_INDIVIDUAL_PRIVACY = 'GET_INDIVIDUAL_PRIVACY';

export const SET_INDIVIDUAL_BASIC_INFO = 'SET_INDIVIDUAL_BASIC_INFO';
export const SET_INDIVIDUAL_INVOLVEMENT = 'SET_INDIVIDUAL_INVOLVEMENT';
export const SET_INDIVIDUAL_PRIVACY = 'SET_INDIVIDUAL_PRIVACY';

export const CLEAR_INDIVIDUAL_BASIC_INFO = 'CLEAR_INDIVIDUAL_BASIC_INFO';
export const CLEAR_INDIVIDUAL_INVOLVEMENT = 'CLEAR_INDIVIDUAL_INVOLVEMENT';
export const CLEAR_INDIVIDUAL_PRIVACY = 'CLEAR_INDIVIDUAL_PRIVACY';

export const GET_ALL_INDIVIDUALS = 'GET_ALL_INDIVIDUALS';
export const GET_INDIVIDUAL_PUBLIC_INFO = 'GET_INDIVIDUAL_PUBLIC_INFO';

// ORGANIZATION
export const GET_ORGANIZATION_BASIC_INFO = 'GET_ORGANIZATION_BASIC_INFO';
export const GET_ORGANIZATION_SERVICE_INFO = 'GET_ORGANIZATION_SERVICE_INFO';
export const GET_ORGANIZATION_INTERNAL_LINK = 'GET_ORGANIZATION_INTERNAL_LINK';

export const SET_ORGANIZATION_BASIC_INFO = 'SET_ORGANIZATION_BASIC_INFO';
export const SET_ORGANIZATION_SERVICE_INFO = 'SET_ORGANIZATION_SERVICE_INFO';
export const SET_ORGANIZATION_INTERNAL_LINK = 'SET_ORGANIZATION_INTERNAL_LINK';

export const CLEAR_ORGANIZATION_BASIC_INFO = 'CLEAR_ORGANIZATION_BASIC_INFO';
export const CLEAR_ORGANIZATION_SERVICE_INFO = 'CLEAR_ORGANIZATION_SERVICE_INFO';
export const CLEAR_ORGANIZATION_INTERNAL_LINK = 'CLEAR_ORGANIZATION_INTERNAL_LINK';

export const GET_ALL_ORGANIZATIONS = 'GET_ALL_ORGANIZATIONS';
export const GET_ORGANIZATION_PUBLIC_INFO = 'GET_ORGANIZATION_PUBLIC_INFO';
export const GET_ALL_SUGGESTED_ORGANIZATIONS = 'GET_ALL_SUGGESTED_ORGANIZATIONS';

// EVENTS
export const GET_EVENT = 'GET_EVENT';
export const SET_EVENT = 'SET_EVENT';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const CLEAR_EVENT = 'CLEAR_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';

// Follow
export const FOLLOW_USER = 'FOLLOW_USER';
export const UNFOLLOW_USER = 'UNFOLLOW_USER';
export const GET_ALL_FOLLOWERS = 'GET_ALL_FOLLOWERS';
export const GET_ALL_FOLLOWINGS = 'GET_ALL_FOLLOWINGS';
export const CHECK_IF_FOLLOWER = 'CHECK_IF_FOLLOWER';

// PROJECTS
export const GET_PROJECT = 'GET_PROJECT';
export const SET_PROJECT = 'SET_PROJECT';
export const GET_ALL_PROJECTS = 'GET_ALL_PROJECTS';
export const CLEAR_PROJECT = 'CLEAR_PROJECT';
export const DELETE_PROJECT = 'DELETE_PROJECT';

// POSTS
export const GET_POST = 'GET_POST';
export const SET_POST = 'SET_POST';
export const GET_ALL_POSTS = 'GET_ALL_POSTS';
export const CLEAR_POST = 'CLEAR_POST';
export const DELETE_POST = 'DELETE_POST';
export const HOME_FEED = 'HOME_FEED';
export const GET_ALL_SUGGESTED_POSTS = 'GET_ALL_SUGGESTED_POSTS';

export const LIKE_POST = 'LIKE_POST';
export const CANCEL_LIKE_POST = 'CANCEL_LIKE_POST';

export const INTERESTED_POST = 'INTERESTED_POST';
export const CANCEL_INTERESTED_POST = 'CANCEL_INTERESTED_POST';

export const GOING_POST = 'GOING_POST';
export const CANCEL_GOING_POST = 'CANCEL_GOING_POST';

export const CHANGE_POST_INTEREST = 'CHANGE_POST_INTEREST';

export const GET_TOP_NOTIFICATIONS = 'GET_TOP_NOTIFICATIONS';
export const GET_ALL_NOTIFICATIONS = 'GET_ALL_NOTIFICATIONS';
export const GET_NOTIFICATIONS_COUNT = 'GET_NOTIFICATIONS_COUNT';
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const SET_NOTIFICATION_LOCAL = 'SET_NOTIFICATION_LOCAL';
