export const USER_SIGN_IN = 'USER_SIGN_IN';
export const USER_SIGN_UP = 'USER_SIGN_UP';
export const USER_SIGN_OUT = 'USER_SIGN_OUT';
export const USER_AUTH = 'USER_AUTH';
export const SET_USER = 'SET_USER';
export const GET_USER = 'GET_USER';
export const GET_ALL_USERS = 'GET_ALL_USERS';
export const DELETE_USER = 'DELETE_USER';
export const CLEAR_USER = 'CLEAR_USER';
export const CLEAR_ALL_USERS = 'CLEAR_ALL_USERS';
export const CHANGE_PASSWORD = 'CHANGE_PASSWORD';
export const RECOVER_PASSWORD = 'RECOVER_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';

export const GET_ALL_AREA_OF_INTEREST = 'GET_ALL_AREA_OF_INTEREST';

export const GET_ALL_GLOBAL_IMPACT_AREAS = 'GET_ALL_GLOBAL_IMPACT_AREAS';
export const GET_ALL_IMPACT_AREAS_BY_USER = 'GET_ALL_IMPACT_AREAS_BY_USER';

export const GET_ALL_ORGANIZATION_TYPES = 'GET_ALL_ORGANIZATION_TYPES';

// INDIVIDUAL
export const GET_INDIVIDUAL_BASIC_INFO = 'GET_INDIVIDUAL_BASIC_INFO';
export const GET_INDIVIDUAL_INVOLVEMENT = 'GET_INDIVIDUAL_INVOLVEMENT';
export const GET_INDIVIDUAL_PRIVACY = 'GET_INDIVIDUAL_PRIVACY';

export const SET_INDIVIDUAL_BASIC_INFO = 'SET_INDIVIDUAL_BASIC_INFO';
export const SET_INDIVIDUAL_INVOLVEMENT = 'SET_INDIVIDUAL_INVOLVEMENT';
export const SET_INDIVIDUAL_PRIVACY = 'SET_INDIVIDUAL_PRIVACY';

export const CLEAR_INDIVIDUAL_BASIC_INFO = 'CLEAR_INDIVIDUAL_BASIC_INFO';
export const CLEAR_INDIVIDUAL_INVOLVEMENT = 'CLEAR_INDIVIDUAL_INVOLVEMENT';
export const CLEAR_INDIVIDUAL_PRIVACY = 'CLEAR_INDIVIDUAL_PRIVACY';

export const GET_ALL_INDIVIDUALS = 'GET_ALL_INDIVIDUALS';
export const GET_INDIVIDUAL_PUBLIC_INFO = 'GET_INDIVIDUAL_PUBLIC_INFO';

// ORGANIZATION
export const GET_ORGANIZATION_BASIC_INFO = 'GET_ORGANIZATION_BASIC_INFO';
export const GET_ORGANIZATION_SERVICE_INFO = 'GET_ORGANIZATION_SERVICE_INFO';
export const GET_ORGANIZATION_INTERNAL_LINK = 'GET_ORGANIZATION_INTERNAL_LINK';

export const SET_ORGANIZATION_BASIC_INFO = 'SET_ORGANIZATION_BASIC_INFO';
export const SET_ORGANIZATION_SERVICE_INFO = 'SET_ORGANIZATION_SERVICE_INFO';
export const SET_ORGANIZATION_INTERNAL_LINK = 'SET_ORGANIZATION_INTERNAL_LINK';

export const CLEAR_ORGANIZATION_BASIC_INFO = 'CLEAR_ORGANIZATION_BASIC_INFO';
export const CLEAR_ORGANIZATION_SERVICE_INFO = 'CLEAR_ORGANIZATION_SERVICE_INFO';
export const CLEAR_ORGANIZATION_INTERNAL_LINK = 'CLEAR_ORGANIZATION_INTERNAL_LINK';

export const GET_ALL_ORGANIZATIONS = 'GET_ALL_ORGANIZATIONS';
export const GET_ORGANIZATION_PUBLIC_INFO = 'GET_ORGANIZATION_PUBLIC_INFO';

// EVENTS
export const GET_EVENT = 'GET_EVENT';
export const SET_EVENT = 'SET_EVENT';
export const GET_ALL_EVENTS = 'GET_ALL_EVENTS';
export const CLEAR_EVENT = 'CLEAR_EVENT';
export const DELETE_EVENT = 'DELETE_EVENT';
