exports.ImpactAreas = [
    'Animal Welfare',
    'Arts',
    'Children',
    'Civil Rights',
    'Community Development',
    'Crime and Public Safety',
    'Culture',
    'Disabilities',
    'Economic Development',
    'Education',
    'Elderly',
    'Food & Hunger',
    'Healthcare',
    'History',
    'Homelessness',
    'Human Services',
    'Immigrants and Refugees',
    'Law and Policy',
    'Mental Health',
    'Parks and pen Space',
    'Poverty Housing',
    'Public Health',
    'Racial Justice',
    'Religion',
    'Sports and Recreations',
    'Women and Girls',
    'Workforce Development',
    'Environment',
    'Veterans',
    'LGBTQ',
];
