exports.ImpactAreas = [
    'Animal Welfare',
    'Arts',
    'Children',
    'Civil Rights',
    'Community Development',
    'Crime and Public Safety',
    'Culture',
    'Disabilities',
    'Economic Development',
    'Education',
    'Elderly',
    'Food and Hunger',
    'Healthcare',
    'History',
    'Homelessness',
    'Housing',
    'Human Services',
    'Immigrants and Refugees',
    'Law and Policy',
    'Mental Health',
    'Parks and Open Spaces',
    'Poverty',
    'Public Health',
    'Racial Justice',
    'Religion',
    'Sports and Recreation',
    'Women and Gender Rights',
    'Workforce Development',
    'Environment',
    'Veterans',
    'LGBTQ',
];

exports.OrganizationTypes = [
    'Non-Profit',
    'Community Group',
    'Political Organization',
    'Government',
    'Religious',
    'Arts Organization',
    'School',
    'Club/Association',
    'Foundation',
];

exports.Skills = [
    'Accounting',
    'Advocacy',
    'Bilingual',
    'Business',
    'Corporate Relations',
    'Community Connections',
    'Community Organizing',
    'Data Analytics',
    'Education & After School Programs',
    'Event Planning',
    'Finance',
    'Fund Raising',
    'Government Relations',
    'Grant Writing',
    'Graphic Design',
    'Health Care/Public Health',
    'Human Resource Management',
    'Information Technology',
    'Legal',
    'Marketing',
    'Media & Public Relations',
    'Non-Profit Management',
    'Policy',
    'Program Management',
    'Real Estate',
    'Research & Evaluation',
    'Sales',
    'Social Services',
    'Strategic Planning',
    'Web & Social Media',
    'Writing',
];
exports.Languages = [
    'English',
    'Spanish',
    'Mandarin',
    'Cantonese',
    'Vietnamese',
    'Russian',
    'Arabic',
    'Haitan',
    'French',
    'Khmer',
    'Malayalam',
    'Kannada',
    'Portuguese',
    'Korean',
    'Italian',
    'Bengali',
    'Ukranian',
    'Tagalog',
    'Gujarati',
    'Amharic',
    'Somali',
    'Hindi',
    'Polish',
    'Urdu',
    'Swahili',
    'Nepali',
    'Martathi',
    'Tamil',
    'Japanese',
    'Hebrew',
    'Telugu',
    'Thai',
    'Lao',
];
