exports.ImpactAreas = [
    'Animal Welfare',
    'Arts',
    'Children',
    'Civil Rights',
    'Community Development',
    'Crime and Public Safety',
    'Culture',
    'Disabilities',
    'Economic Development',
    'Education',
    'Elderly',
    'Food and Hunger',
    'Healthcare',
    'History',
    'Homelessness',
    'Housing',
    'Human Services',
    'Immigrants and Refugees',
    'Law and Policy',
    'Mental Health',
    'Parks and Open Spaces',
    'Poverty',
    'Public Health',
    'Racial Justice',
    'Religion',
    'Sports and Recreation',
    'Women and Gender Rights',
    'Workforce Development',
    'Environment',
    'Veterans',
    'LGBTQ',
];

exports.OrganizationTypes = ['Non-Profit', 'Community Group', 'Political Organization', 'Government', 'Religious', 'Arts Organization', 'School', 'Club/Association', 'Foundation'];
